name: Auto Merge

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable PR automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          merge-method: squash
      - name: Merge pull request
        uses: peter-evans/pull-request-merge@v3
        with:
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          merge-method: squash
